# Use an official Python runtime as a parent image
FROM python:3.10

# Install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    git \
    bash \
    && rm -rf /var/lib/apt/lists/*

# Install Git LFS
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get update && apt-get install -y git-lfs && \
    git lfs install

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to PATH
ENV PATH="/root/.local/bin:$PATH"

# Configure Poetry to create virtual environments in the project directory
RUN poetry config virtualenvs.in-project true

# Set up a working directory
WORKDIR /app

# Copy project files
COPY . /app/

# Recreate and install project dependencies
RUN poetry env use python && poetry install --no-root

# Set environment variables to activate the virtual environment automatically
ENV VIRTUAL_ENV="/app/.venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Set Metaflow user
ENV METAFLOW_USER=ychernushenko

# Install Metaflow and boto3
RUN pip install metaflow boto3

# Copy the script to retrieve secrets
COPY src/utils/retrieve_secrets.py /app/retrieve_secrets.py

# Default command to run the script, login to Hugging Face, and start the container
ENTRYPOINT ["bash", "-c", "python /app/retrieve_secrets.py && poetry run huggingface-cli login --token \"$HF_TOKEN\" --add-to-git-credential && exec python"]